services:
  opensearch-dashboards:
    environment:
      OPENSEARCH_SSL_VERIFICATIONMODE: full

  logstash:
    environment:
      OPENSEARCH_SSL_VERIFY: true

  opensearch-bootstrap:
    profiles:
      - bootstrap
